import * as Yup from 'yup';

const addMicsValidationSchema = {
  MICS_2020_No: Yup.string().required('MICS Number is required'),
  MICS_2021_No: Yup.string().required('MICS Number is required'),
  Control_ID: Yup.string().required('Control ID is required'),
  Mega_Process: Yup.string().required('Mega Process is required'),
  Category: Yup.string().required('Category is required'),
  Change_Size: Yup.string().required('Change_Size is required'),
  DTC: Yup.string().required('DTC is required'),
  Reviewed: Yup.string().required('Reviewed is required'),
  ABI_Key: Yup.string().required('ABI Key is required'),
  Ambev_Key: Yup.string().required('Ambev Key is required'),
  FCPA: Yup.string().required('FCPA is required'),
  Frequency: Yup.string().required('Frequency is required'),
  Preventive_Detective: Yup.string().required('Preventive Detective is required'),
  Automation: Yup.string().required('Automation is required'),
  Recommended_Level: Yup.string().required('Recommended Level is required'),
  Maturity_Relevant: Yup.string().required('Maturity Relevant is required'),
  mics_weight: Yup.string().required('mics weight is required'),
  Recommended_Standardization: Yup.string().required('Recommended Standardization is required'),
  ABI_DAG: Yup.string().required('ABI DAG is required'),
  AmBev_DAG: Yup.string().required('AmBev DAG is required'),
  B2B: Yup.string().required('B2B is required'),
  Fintech: Yup.string().required('Fintech is required'),
  Control_Split: Yup.string().required('Control Split is required'),
  Sub_Process: Yup.string().required('Sub Process is required'),
  Risk: Yup.string().required('Risk is required'),
  Control_name: Yup.string().required('Control name is required'),
  mics_L1desc: Yup.string().required('mics L1 desc is required'),
  mics_L2desc: Yup.string().required('mics L2 desc is required'),
  mics_L3desc: Yup.string().required('mics L3 desc is required'),
  BS_impact: Yup.string().required('BS impact is required'),
  PnL_impact: Yup.string().required('PnL impact is required'),
  Cash_flow_impact: Yup.string().required('Cash flow impact is required'),
  testing_approach: Yup.string().required('testing approach is required'),
  L3_KPI: Yup.string().required('L3 KPI is required'),
  L2_KPI: Yup.string().required('L2 KPI is required'),
  L1_KPI: Yup.string().required('L1 KPI is required'),
  Kpi_status: Yup.string().required('Kpi status  is required'),
  change_comment: Yup.string().required('change comment is required'),
};

export { addMicsValidationSchema };
