export const formTemplate = {
  managerDetails: {
    managerEmpCode: '',
    managerMobile: '',
    managerTower: '',
    managerTeamFamilyCovidPosSuspect: '',
  },
  teamMemberDetails: {
    teamMemberName: '',
    teamMemberEmpCode: '',
    teamMemberTower: '',
    teamMemberMobile: '',
    teamMemberCurrStateCode: '',
    teamMemberCurrState: '',
    teamMemberCurrCity: '',
    teamMemberCovidPosSuspect: '',
    teamMemberInvestigationType: '',
    teamMemberComorbidities: '',
    teamMemberLeaveWorking: '',
    teamMemberLeaveStartDate: '',
    teamMemberLeaveEndDate: '',
    teamMemberContactedCareRoom: '',
    teamMemberBCP: '',
    teamMemberZone: '',
    teamMemberBackup: '',
    teamMemberImpact: '',
    teamMemberImpactDetails: '',
  },
  teamMemberFamilyDetails: {
    teamMemberFamilyPositiveSuspect: '',
    // teamMemberFamilyPositiveSuspectPeople: '',
    teamMemberFamilyPositivePeople: '',
    teamMemberFamilySuspectPeople: '',
    teamMemberFamilyRelation: '',
    teamMemberFamilyCurrState: '',
    teamMemberFamilyCurrStateCode: '',
    teamMemberFamilyCurrCity: '',
    teamMemberSupportRequest: '',
    teamMemberRemarks: '',
  },
  medicalDetails: {
    reportingDateMedicalCenter: '',
    vp: '',
    covidStatus: '', // have to check this
    gccActions: '',
    positiveTestDate: '',
    firstSymptomsDate: '',
    familyLivingSameBuilding: '',
    teamMemberFamilyHospitalized: '',
    teamMemberFamilyContactedGCCMedCenter: '', // is this same as your care room question in team member section
    patientFeelingToday: '',
    scheduledAppointmentGccVirtualDoc: '',
    nonMedicalSupport: '', // this should be covered under teamMemberSupportRequest
    relevantInfo: '', // could be same as teamMemberRemarks
    gccDocRiskAssessment: '',
    bedReq: '',
    completed28Days: '',
    recoveryStatusEmployee: '',
    feelingToWork: '',
    callingPerson: '',
  },
  emergencySupportDetails: {
    medicalConsultationRequired: '',
    oxygenRequired: '',
    foodRequired: '',
    covidCareCenterRequired: '',
    covidTestRequired: '',
    otherAssistanceRequired: '',
  },
}

export const vaccinationRequestTemplate = {
  dependentId: '',
  dependentName: '',
  dependentRelation: '',
  doseNumber: '',
  vaccinationPreference: '',
  bookDate: '',
  bookSlot: '',
  Transport: '',
  dateofFirstDose: '',
  firstDoseTaken: '',
  firstVaccineDose: '',
}