export const towers = [
  'APPLICATIONS',
  'ATR',
  'Digital Solutions',
  'BUSINESS TRANSFORMATION',
  'Business Transformation Africa',
  'COMPLIANCE',
  'CP&A',
  'CSM',
  'CYBER SECURITY OPERATIONS',
  'DATA & ARCHITECTURE',
  'DIGITAL WORKPLACE',
  'EMPLOYEE EXPERIENCE',
  'FINANCE',
  'FP&A',
  'GAC',
  'GLOBAL COMMAND CENTER',
  'GLOBAL PROCUREMENT',
  'GLOBAL SALES INFOCELL',
  'GPSS',
  'IT',
  'LEGAL & COMPLIANCE',
  'MDM',
  'NETWORK OPERATIONS',
  'NEW CAPABILITIES',
  'NEW CAPABILITIES INNOVATION',
  'NOCC SUPPORT',
  'OPERATIONS-OTHERS',
  'OTC',
  'PBS',
  'PEOPLE',
  'PEOPLE - REWARDS',
  'PEOPLE TECH',
  'PROCUREMENT',
  'PTP',
  'ROA OPERATIONS',
  'SALESFORCE C4E',
  'SAP',
  'TECH LOGISTICS',
  'TECH SUPPLY',
]

export const serviceAreas = [
  'Operations',
  'Emp Experience & People Tech',
  'PEOPLE',
  'PROCUREMENT',
  'SAP',
  'Tech Log & Supply',
  'DATA & ARCHITECTURE',
  'IT Ops',
  'GAC',
]

export const teamMemberInvestigationTypes = [
  'Covid-19 Positive - Home Quarantine',
  'Covid-19 Positive - Hospitalized',
  'Covid-19 Positive - Need support from Organization',
  'Covid-19 Suspect - Test report awaited',
  'Covid-19 Suspect - Need Support for testing',
]

export const zones = ['NAZ', 'MAZ', 'SAZ', 'APAC', 'EUR', 'AFR', 'GLOBAL']
